import { createContext, useContext, useId, type ReactNode } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaView } from 'react-native-safe-area-context';
import Svg, { Defs, RadialGradient, Stop, Rect, Path } from 'react-native-svg';

export const colors = { bg:'#F4E6DD', surface:'#FFF5ED', ink:'#182C24', muted:'#71665F', line:'#DDC9BB', accent:'#17362A', onAccent:'#FFF4E9', selected:'#E8C9B8', bloomBg:'#101D18', rose:'#D8A99B', champagne:'#E8C9A4' };
export const serif = Platform.select({ ios:'Georgia', android:'serif', default:'Georgia, Times New Roman, serif' });
const Dark = createContext(false);
export function Screen({children, scroll=true, footer, dark=false}: {children:ReactNode;scroll?:boolean;footer?:ReactNode;dark?:boolean}) {
  const ambienceId = useId().replace(/[^a-zA-Z0-9]/g, '') + 'ambience';
  return <Dark.Provider value={dark}><SafeAreaView style={[s.safe,{backgroundColor:dark?colors.bloomBg:colors.bg}]}>
    <StatusBar style={dark?'light':'dark'} />
    {dark && <View pointerEvents="none" accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={StyleSheet.absoluteFill}><Svg width="100%" height="100%" preserveAspectRatio="xMidYMid slice" viewBox="0 0 400 850"><Defs><RadialGradient id={ambienceId}><Stop offset="0" stopColor="#9A8060" stopOpacity=".22"/><Stop offset="1" stopColor="#101D18" stopOpacity="0"/></RadialGradient></Defs><Rect width="400" height="850" fill="#101D18"/><Rect x="-170" y="-160" width="740" height="940" fill={'url(#'+ambienceId+')'}/><Path d="M0 680 C140 600 0 400 80 320 C120 480 180 610 0 730 M400 480 C260 410 410 260 330 170 C290 300 220 390 400 520" fill="#73927A" opacity=".055"/></Svg></View>}
    <View style={s.frame}>{scroll?<ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{flexGrow:1}}><View style={s.inner}>{children}</View></ScrollView>:<View style={s.inner}>{children}</View>}{footer}</View>
  </SafeAreaView></Dark.Provider>;
}
export function Title({children}:{children:ReactNode}) { const dark=useContext(Dark); return <Text accessibilityRole="header" style={[s.title,{color:dark?colors.onAccent:colors.ink}]}>{children}</Text>; }
export function Body({children,muted}:{children:ReactNode;muted?:boolean}) {const dark=useContext(Dark);return <Text style={[s.body,{color:dark?(muted?'#C6C4B8':colors.onAccent):(muted?colors.muted:colors.ink)}]}>{children}</Text>;}
export function Label({children}:{children:ReactNode}) {const dark=useContext(Dark);return <Text style={[s.label,{color:dark?'#C6B399':colors.muted}]}>{children}</Text>;}
export function Button({title,onPress,variant='primary',disabled}:{title:string;onPress:()=>void;variant?:'primary'|'ghost';disabled?:boolean}) {const dark=useContext(Dark);return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.btn,{backgroundColor:variant==='ghost'?(dark?'#FFFFFF08':colors.surface):(dark?'#EED0BC':colors.accent),borderColor:dark?'#E7D1B52B':colors.line,borderWidth:variant==='ghost'?1:0},(pressed||disabled)&&{opacity:.55}]}><Text style={{fontSize:15,fontWeight:'500',color:variant==='ghost'?(dark?colors.onAccent:colors.ink):(dark?colors.ink:colors.onAccent)}}>{title}</Text></Pressable>;}
export function Choice({label,sub,selected,onPress}:{label:string;sub?:string;selected:boolean;onPress:()=>void}) {return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected,selected}} onPress={onPress} style={[s.choice,selected&&{backgroundColor:'#EBD3C3',borderColor:'#927A63'}]}><View style={{flex:1,gap:5}}><Text style={s.choiceLabel}>{label}</Text>{sub&&<Text style={s.choiceSub}>{sub}</Text>}</View><View style={{width:20,height:20,borderRadius:10,borderWidth:1,borderColor:selected?colors.accent:'#BBA99B',backgroundColor:selected?colors.accent:'transparent',alignItems:'center',justifyContent:'center'}}>{selected&&<Text style={{color:colors.onAccent,fontSize:12}}>✓</Text>}</View></Pressable>;}
export function Field(props:TextInputProps & {label:string}) {const {label,...rest}=props;return <View style={{gap:8}}><Label>{label}</Label><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} style={s.input} {...rest}/></View>;}
export function Card({children,dark}:{children:ReactNode;dark?:boolean}) {const inherited=useContext(Dark);const isDark=dark??inherited;return <Dark.Provider value={isDark}><View style={[s.card,isDark&&{backgroundColor:'#D6DAC00D',borderColor:'#D9C3A629'}]}>{children}</View></Dark.Provider>;}
const s=StyleSheet.create({safe:{flex:1},frame:{flex:1,width:'100%',maxWidth:480,alignSelf:'center'},inner:{flex:1,paddingHorizontal:24,paddingTop:28,paddingBottom:28,gap:18},title:{fontFamily:serif,fontSize:32,lineHeight:38,fontWeight:'400',letterSpacing:-.7},body:{fontSize:14,lineHeight:22},label:{fontSize:10,fontWeight:'600',letterSpacing:2,textTransform:'uppercase'},btn:{minHeight:52,borderRadius:30,alignItems:'center',justifyContent:'center',paddingHorizontal:20},choice:{minHeight:78,flexDirection:'row',alignItems:'center',gap:16,borderRadius:22,borderWidth:1,borderColor:'#E4D0C2',backgroundColor:'#FFF6EDB8',paddingHorizontal:20,paddingVertical:17},choiceLabel:{fontSize:16,fontWeight:'500',color:colors.ink},choiceSub:{fontSize:12,lineHeight:18,color:colors.muted},input:{minHeight:54,borderRadius:17,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:16,fontSize:16,color:colors.ink},card:{borderRadius:22,borderWidth:1,borderColor:'#E4D0C2',backgroundColor:'#FFF5EDBB',padding:18,gap:8}});
